apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
spec:
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: will-app-svc
spec:
  type: LoadBalancer
  selector:
    app: will
  ports:
  - name: app-port
    port: 8888
    targetPort: 8888

